services:
  pyspark:
    build: .
    image: pyspark-app:latest
    container_name: pyspark-container
    command: pyspark --master local[*] --conf spark.eventLog.enabled=true --conf spark.eventLog.dir=/spark-events
    ports:
      - "4040:4040"
    volumes:
      - ./src:/app/src:rw
      - ./data:/app/data:rw
      - ./spark-events:/spark-events:rw
    working_dir: /app
    stdin_open: true
    tty: true

  history-server:
    image: pyspark-app:latest
    container_name: spark-history
    working_dir: /opt/spark-4.1.1-bin-hadoop3
    command: >
      bash -c "mkdir -p /spark-events &&
               ./bin/spark-class org.apache.spark.deploy.history.HistoryServer"
    environment:
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=/spark-events
    ports:
      - "18080:18080"
    volumes:
      - ./spark-events:/spark-events:rw
